import { Trend, User, Vertical } from './types';

export const VERTICALS: Vertical[] = [
  { id: 'v1', name: 'Healthcare', slug: 'healthcare', color: 'bg-emerald-500' },
  { id: 'v2', name: 'Financial Services', slug: 'financial-services', color: 'bg-blue-500' },
  { id: 'v3', name: 'Retail', slug: 'retail', color: 'bg-orange-500' },
  { id: 'v4', name: 'Manufacturing', slug: 'manufacturing', color: 'bg-slate-500' },
  { id: 'v5', name: 'Technology', slug: 'technology', color: 'bg-purple-500' },
  { id: 'v6', name: 'Legal', slug: 'legal', color: 'bg-indigo-500' },
  { id: 'v7', name: 'Education', slug: 'education', color: 'bg-yellow-500' },
  { id: 'v8', name: 'Government', slug: 'government', color: 'bg-red-500' },
  { id: 'v9', name: 'Energy', slug: 'energy', color: 'bg-green-500' },
  { id: 'v10', name: 'Media', slug: 'media', color: 'bg-pink-500' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Marcus Partner',
    email: 'marcus@consulting.com',
    role: 'user',
    avatar: 'https://i.pravatar.cc/150?u=marcus',
  },
  {
    id: 'u2',
    name: 'Sarah Strategy',
    email: 'sarah@consulting.com',
    role: 'user',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
  },
  {
    id: 'admin1',
    name: 'Admin User',
    email: 'admin@lighthouse.com',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?u=admin',
  },
];

export const MOCK_TRENDS: Trend[] = [
  {
    id: 't1',
    title: 'Generative AI in Regulatory Compliance',
    justificationSummary: 'Financial institutions are rapidly adopting LLMs to automate compliance checks and regulatory reporting. This shift is driven by the increasing complexity of global regulations and the need to reduce operational costs. Early adopters are seeing a 40% reduction in manual review time and improved accuracy in detecting anomalies.',
    whyTrend: 'Regulatory complexity is increasing globally while compliance budgets are shrinking. Generative AI offers a scalable solution to interpret and apply complex regulations in real-time, a capability that traditional rule-based systems lack. We identified this as a top trend based on a surge in patent filings related to "AI compliance" and recent earnings call mentions from major banks like JPMorgan and Citi.',
    howConsultanciesLeverage: 'Consultancies can offer "Compliance-as-a-Service" platforms powered by GenAI, or provide implementation services for custom compliance bots. There is also a significant opportunity in auditing these AI systems for hallucination risks.',
    analysisDetail: 'The convergence of LLMs with regulatory technology (RegTech) is creating a new paradigm. Unlike previous waves of automation that relied on structured data, GenAI can parse unstructured regulatory texts, policy documents, and communication logs. This allows for "intent-based" compliance monitoring rather than just keyword matching. However, the "black box" nature of these models poses a challenge, necessitating new governance frameworks that consultancies are well-positioned to design.',
    affectedVerticals: ['v2', 'v6', 'v8'],
    sourceUrl: 'https://example.com/genai-compliance',
    additionalSources: [
      { id: 's1', title: 'The Future of RegTech', url: 'https://example.com/regtech', publisher: 'Financial Times', date: '2023-10-10' },
      { id: 's2', title: 'AI in Banking Report', url: 'https://example.com/ai-banking', publisher: 'McKinsey', date: '2023-09-15' }
    ],
    status: 'current',
    dateAdded: '2023-10-15T10:00:00Z',
    author: 'Financial Times',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't2',
    title: 'AI-Driven Drug Discovery Acceleration',
    justificationSummary: 'Pharma giants are partnering with AI startups to shorten drug discovery timelines from years to months. Several AI-designed drugs are now entering clinical trials, validating the technology\'s potential to revolutionize R&D productivity and reduce the $2B+ cost of bringing a new drug to market.',
    whyTrend: 'The traditional drug discovery process is prohibitively expensive and slow, with a high failure rate. AI models can predict molecular interactions with high accuracy, significantly narrowing the search space for potential candidates. This trend is evidenced by multi-billion dollar partnerships between big pharma (e.g., Pfizer, Sanofi) and AI-native biotechs.',
    howConsultanciesLeverage: 'Strategy firms can advise pharma companies on "AI-first" R&D operating models. Tech consultancies can build the data infrastructure required to train proprietary models on internal research data.',
    analysisDetail: 'AI is moving beyond simple screening to de novo molecule generation. Generative models can design novel protein structures that have never existed in nature but bind perfectly to disease targets. This "inverse design" approach flips the traditional discovery model on its head. The challenge now shifts from discovery to validation, where AI is also being used to simulate clinical trials and predict patient responses.',
    affectedVerticals: ['v1', 'v5'],
    sourceUrl: 'https://example.com/ai-drug-discovery',
    additionalSources: [
      { id: 's3', title: 'AI in Biotech', url: 'https://example.com/biotech', publisher: 'Nature Biotechnology', date: '2023-10-05' }
    ],
    status: 'current',
    dateAdded: '2023-10-18T14:30:00Z',
    author: 'Nature Biotechnology',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't3',
    title: 'Hyper-Personalization in Retail at Scale',
    justificationSummary: 'Retailers are moving beyond simple recommendation engines to real-time, generative content creation for individual shoppers. This allows for dynamic product descriptions, personalized marketing imagery, and 1:1 shopping assistants that mimic human stylists.',
    whyTrend: 'Consumers increasingly expect personalized experiences, but manual customization is unscalable. GenAI allows retailers to generate unique content for every user on the fly. We see this trend gaining traction with major e-commerce platforms integrating image generation tools and conversational search interfaces.',
    howConsultanciesLeverage: 'Marketing consultancies can help brands design "segment-of-one" customer journeys. Implementation partners are needed to integrate GenAI tools with existing e-commerce platforms and CDPs.',
    analysisDetail: 'The shift is from "predictive" personalization (guessing what you might like) to "generative" personalization (creating what you want). This involves real-time rendering of products in contexts relevant to the user (e.g., showing a tent in a forest for a hiker vs. a backyard for a family). This level of personalization requires a robust data foundation and low-latency inference infrastructure.',
    affectedVerticals: ['v3', 'v10'],
    sourceUrl: 'https://example.com/retail-personalization',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-10-20T09:15:00Z',
    author: 'Retail Dive',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't4',
    title: 'Autonomous Supply Chain Agents',
    justificationSummary: 'Manufacturing and logistics are deploying autonomous AI agents that can negotiate with suppliers and re-route shipments without human intervention. These agents operate 24/7 to optimize for cost, speed, and carbon footprint simultaneously.',
    whyTrend: 'Supply chain disruptions are becoming the norm due to geopolitical instability and climate change. Autonomous agents provide the speed and responsiveness needed to adapt to shocks in real-time, which human teams cannot match. This trend is supported by the rise of "Agentic AI" frameworks.',
    howConsultanciesLeverage: 'Operations consultants can redesign supply chain processes to accommodate autonomous decision-making. Change management is critical here as human roles shift from execution to oversight.',
    analysisDetail: 'Unlike traditional optimization software that suggests actions, autonomous agents execute them. They can negotiate spot rates with carriers, trigger re-orders based on predictive demand, and dynamically adjust production schedules. The key innovation is the ability of these agents to communicate with each other across organizational boundaries, creating a self-healing supply network.',
    affectedVerticals: ['v4', 'v3', 'v9'],
    sourceUrl: 'https://example.com/autonomous-supply-chain',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-10-22T11:45:00Z',
    author: 'Supply Chain Management Review',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't5',
    title: 'AI in Predictive Maintenance for Energy Grids',
    justificationSummary: 'Utility companies are using AI to predict equipment failures before they happen, preventing outages and reducing maintenance costs. This is critical for managing the variable loads introduced by renewable energy sources.',
    whyTrend: 'Aging infrastructure and the integration of renewable energy sources are stressing power grids. AI provides the predictive capabilities needed to maintain reliability in a complex, decentralized grid. Regulatory pressure for grid reliability is a major driver.',
    howConsultanciesLeverage: 'Engineering consultancies can implement IoT sensor networks and AI analytics platforms. Strategy firms can advise on the business case for grid modernization investments.',
    analysisDetail: 'The grid is becoming a bi-directional network with the addition of solar panels and EVs. Traditional grid management software struggles with this complexity. AI models trained on historical weather data, load patterns, and sensor readings can predict transformer failures weeks in advance, allowing for planned maintenance instead of emergency repairs.',
    affectedVerticals: ['v9', 'v8'],
    sourceUrl: 'https://example.com/energy-predictive-maintenance',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-10-25T16:20:00Z',
    author: 'Energy World',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't6',
    title: 'Legal Tech: Automated Contract Review',
    justificationSummary: 'Law firms and corporate legal departments are adopting AI tools that can review contracts and flag risks in seconds. This automation is commoditizing routine legal work and shifting value to high-level advisory services.',
    whyTrend: 'Legal review is a major bottleneck in business transactions. AI can handle routine contract review faster and more consistently than junior lawyers, freeing them for higher-value work. The explosion of legal-specific LLMs (e.g., Harvey AI) confirms this trend.',
    howConsultanciesLeverage: 'Legal tech consultancies can help firms select and train AI models on their specific contract templates. There is also a market for "legal operations" consulting to optimize workflows around these new tools.',
    analysisDetail: 'AI is not just searching for keywords; it is understanding the semantic meaning of clauses. It can identify "poison pill" clauses, compare terms against a company\'s playbook, and suggest redlines. This reduces the cost of due diligence in M&A and accelerates sales cycles by speeding up contract negotiations.',
    affectedVerticals: ['v6', 'v2', 'v5'],
    sourceUrl: 'https://example.com/legal-contract-review',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-10-28T08:00:00Z',
    author: 'Legal Tech News',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't7',
    title: 'AI-Powered Personalized Learning',
    justificationSummary: 'EdTech platforms are using AI to create adaptive learning paths that adjust to each student\'s pace and understanding. This mimics the benefits of 1-on-1 tutoring at a mass scale.',
    whyTrend: 'The "one-size-fits-all" model of education is failing many students. AI enables mass personalization, potentially closing achievement gaps and improving learning outcomes. Investment in AI EdTech startups has doubled in the last year.',
    howConsultanciesLeverage: 'Education consultants can help institutions integrate AI tools into their curriculum. There is also a need for policy consulting to address data privacy and ethical concerns in student data.',
    analysisDetail: 'Adaptive learning systems use knowledge graphs to map a student\'s understanding. If a student struggles with a concept, the AI doesn\'t just repeat the lesson; it offers a different explanation, a prerequisite concept, or a practice problem. This continuous feedback loop keeps students in the "zone of proximal development" for optimal learning.',
    affectedVerticals: ['v7', 'v5'],
    sourceUrl: 'https://example.com/ai-education',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-10-30T13:10:00Z',
    author: 'EdSurge',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't8',
    title: 'Generative Design in Manufacturing',
    justificationSummary: 'Engineers are using AI to generate thousands of design variations for parts, optimizing for weight, strength, and material usage. This is enabling the creation of lighter, stronger, and more sustainable products.',
    whyTrend: 'Sustainable manufacturing requires more efficient parts. Generative design can create organic shapes that are impossible for humans to conceive but are lighter and stronger. The adoption of additive manufacturing (3D printing) is a key enabler of this trend.',
    howConsultanciesLeverage: 'Product design firms can adopt these tools to offer superior engineering services. Management consultants can advise on the supply chain implications of using additive manufacturing for these complex parts.',
    analysisDetail: 'Generative design software takes constraints (loads, materials, manufacturing methods) as input and "evolves" a design solution. This often results in alien-looking, organic structures that minimize material usage while maximizing structural integrity. This is particularly valuable in aerospace and automotive industries where weight reduction directly translates to fuel efficiency.',
    affectedVerticals: ['v4', 'v9'],
    sourceUrl: 'https://example.com/generative-design',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-11-02T10:30:00Z',
    author: 'Engineering.com',
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't9',
    title: 'AI in Media Content Creation',
    justificationSummary: 'Media companies are using AI to automate video editing, scriptwriting, and even voice acting. This is democratizing high-quality content creation but raising significant questions about copyright and labor.',
    whyTrend: 'The demand for content is insatiable, but production costs are high. AI tools can democratize high-quality content creation and drastically reduce post-production times. The writers\' and actors\' strikes highlighted the disruptive potential of this technology.',
    howConsultanciesLeverage: 'Media consultancies can help studios implement AI workflows. There is also a significant opportunity in rights management and IP protection consulting for AI-generated content.',
    analysisDetail: 'AI tools can now generate B-roll footage, dub content into multiple languages with the original actor\'s voice, and even de-age actors. This allows for "content atomization," where a single piece of content is automatically repurposed for different platforms and audiences. However, the legal landscape regarding the copyright of AI-generated works remains unsettled.',
    affectedVerticals: ['v10', 'v5'],
    sourceUrl: 'https://example.com/ai-media-creation',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-11-05T15:45:00Z',
    author: 'Variety',
    imageUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't10',
    title: 'Government AI for Public Services',
    justificationSummary: 'Governments are deploying AI chatbots and decision support systems to improve citizen services and reduce bureaucratic backlogs. This is improving access to justice and social services.',
    whyTrend: 'Citizens expect the same level of digital service from government as they get from the private sector. AI can help understaffed agencies deliver better services more efficiently. We are seeing a wave of "GovTech" initiatives globally.',
    howConsultanciesLeverage: 'Public sector consultants can lead digital transformation projects. There is a massive need for "responsible AI" consulting to ensure fairness and transparency in government algorithms.',
    analysisDetail: 'AI is being used to triage 311 calls, process tax returns, and even assist judges in sentencing (though this is controversial). The key challenge is ensuring that these systems do not perpetuate historical biases found in training data. "Explainable AI" is a critical requirement for public sector deployments to maintain public trust.',
    affectedVerticals: ['v8', 'v5', 'v1'],
    sourceUrl: 'https://example.com/government-ai',
    additionalSources: [],
    status: 'current',
    dateAdded: '2023-11-08T09:00:00Z',
    author: 'GovTech',
    imageUrl: 'https://images.unsplash.com/photo-1555848962-6e79363ec58f?auto=format&fit=crop&q=80&w=1000',
  },
];

