import { Trend, User, Vertical } from './types';

export const VERTICALS: Vertical[] = [
  { id: 'v1', name: 'Healthcare', slug: 'healthcare', color: 'bg-emerald-500' },
  { id: 'v2', name: 'Financial Services', slug: 'financial-services', color: 'bg-blue-500' },
  { id: 'v3', name: 'Retail', slug: 'retail', color: 'bg-orange-500' },
  { id: 'v4', name: 'Manufacturing', slug: 'manufacturing', color: 'bg-slate-500' },
  { id: 'v5', name: 'Technology', slug: 'technology', color: 'bg-purple-500' },
  { id: 'v6', name: 'Legal', slug: 'legal', color: 'bg-indigo-500' },
  { id: 'v7', name: 'Education', slug: 'education', color: 'bg-yellow-500' },
  { id: 'v8', name: 'Government', slug: 'government', color: 'bg-red-500' },
  { id: 'v9', name: 'Energy', slug: 'energy', color: 'bg-green-500' },
  { id: 'v10', name: 'Media', slug: 'media', color: 'bg-pink-500' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Marcus Partner',
    email: 'marcus@consulting.com',
    role: 'user',
    avatar: 'https://i.pravatar.cc/150?u=marcus',
  },
  {
    id: 'u2',
    name: 'Sarah Strategy',
    email: 'sarah@consulting.com',
    role: 'user',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
  },
  {
    id: 'admin1',
    name: 'Admin User',
    email: 'admin@lighthouse.com',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?u=admin',
  },
];

export const MOCK_TRENDS: Trend[] = [
  {
    id: 't1',
    title: 'Generative AI in Regulatory Compliance',
    justificationSummary: 'Financial institutions are rapidly adopting LLMs to automate compliance checks and regulatory reporting, reducing costs by up to 40%.',
    whyTrend: 'Regulatory complexity is increasing globally while compliance budgets are shrinking. Generative AI offers a scalable solution to interpret and apply complex regulations in real-time, a capability that traditional rule-based systems lack.',
    howConsultanciesLeverage: 'Consultancies can offer "Compliance-as-a-Service" platforms powered by GenAI, or provide implementation services for custom compliance bots. There is also a significant opportunity in auditing these AI systems for hallucination risks.',
    affectedVerticals: ['v2', 'v6', 'v8'],
    sourceUrl: 'https://example.com/genai-compliance',
    status: 'current',
    dateAdded: '2023-10-15T10:00:00Z',
    author: 'Financial Times',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't2',
    title: 'AI-Driven Drug Discovery Acceleration',
    justificationSummary: 'Pharma giants are partnering with AI startups to shorten drug discovery timelines from years to months, with several AI-designed drugs now entering clinical trials.',
    whyTrend: 'The traditional drug discovery process is prohibitively expensive and slow. AI models can predict molecular interactions with high accuracy, significantly narrowing the search space for potential candidates.',
    howConsultanciesLeverage: 'Strategy firms can advise pharma companies on "AI-first" R&D operating models. Tech consultancies can build the data infrastructure required to train proprietary models on internal research data.',
    affectedVerticals: ['v1', 'v5'],
    sourceUrl: 'https://example.com/ai-drug-discovery',
    status: 'current',
    dateAdded: '2023-10-18T14:30:00Z',
    author: 'Nature Biotechnology',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't3',
    title: 'Hyper-Personalization in Retail at Scale',
    justificationSummary: 'Retailers are moving beyond simple recommendation engines to real-time, generative content creation for individual shoppers.',
    whyTrend: 'Consumers increasingly expect personalized experiences. GenAI allows retailers to generate unique product descriptions, images, and marketing copy for every user on the fly, increasing conversion rates.',
    howConsultanciesLeverage: 'Marketing consultancies can help brands design "segment-of-one" customer journeys. Implementation partners are needed to integrate GenAI tools with existing e-commerce platforms and CDPs.',
    affectedVerticals: ['v3', 'v10'],
    sourceUrl: 'https://example.com/retail-personalization',
    status: 'current',
    dateAdded: '2023-10-20T09:15:00Z',
    author: 'Retail Dive',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't4',
    title: 'Autonomous Supply Chain Agents',
    justificationSummary: 'Manufacturing and logistics are deploying autonomous AI agents that can negotiate with suppliers and re-route shipments without human intervention.',
    whyTrend: 'Supply chain disruptions are becoming the norm. Autonomous agents provide the speed and responsiveness needed to adapt to shocks in real-time, which human teams cannot match.',
    howConsultanciesLeverage: 'Operations consultants can redesign supply chain processes to accommodate autonomous decision-making. Change management is critical here as human roles shift from execution to oversight.',
    affectedVerticals: ['v4', 'v3', 'v9'],
    sourceUrl: 'https://example.com/autonomous-supply-chain',
    status: 'current',
    dateAdded: '2023-10-22T11:45:00Z',
    author: 'Supply Chain Management Review',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't5',
    title: 'AI in Predictive Maintenance for Energy Grids',
    justificationSummary: 'Utility companies are using AI to predict equipment failures before they happen, preventing outages and reducing maintenance costs.',
    whyTrend: 'Aging infrastructure and the integration of renewable energy sources are stressing power grids. AI provides the predictive capabilities needed to maintain reliability in a complex, decentralized grid.',
    howConsultanciesLeverage: 'Engineering consultancies can implement IoT sensor networks and AI analytics platforms. Strategy firms can advise on the business case for grid modernization investments.',
    affectedVerticals: ['v9', 'v8'],
    sourceUrl: 'https://example.com/energy-predictive-maintenance',
    status: 'current',
    dateAdded: '2023-10-25T16:20:00Z',
    author: 'Energy World',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't6',
    title: 'Legal Tech: Automated Contract Review',
    justificationSummary: 'Law firms and corporate legal departments are adopting AI tools that can review contracts and flag risks in seconds.',
    whyTrend: 'Legal review is a major bottleneck in business transactions. AI can handle routine contract review faster and more consistently than junior lawyers, freeing them for higher-value work.',
    howConsultanciesLeverage: 'Legal tech consultancies can help firms select and train AI models on their specific contract templates. There is also a market for "legal operations" consulting to optimize workflows around these new tools.',
    affectedVerticals: ['v6', 'v2', 'v5'],
    sourceUrl: 'https://example.com/legal-contract-review',
    status: 'current',
    dateAdded: '2023-10-28T08:00:00Z',
    author: 'Legal Tech News',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't7',
    title: 'AI-Powered Personalized Learning',
    justificationSummary: 'EdTech platforms are using AI to create adaptive learning paths that adjust to each student\'s pace and understanding.',
    whyTrend: 'The "one-size-fits-all" model of education is failing many students. AI enables mass personalization, potentially closing achievement gaps and improving learning outcomes.',
    howConsultanciesLeverage: 'Education consultants can help institutions integrate AI tools into their curriculum. There is also a need for policy consulting to address data privacy and ethical concerns in student data.',
    affectedVerticals: ['v7', 'v5'],
    sourceUrl: 'https://example.com/ai-education',
    status: 'current',
    dateAdded: '2023-10-30T13:10:00Z',
    author: 'EdSurge',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't8',
    title: 'Generative Design in Manufacturing',
    justificationSummary: 'Engineers are using AI to generate thousands of design variations for parts, optimizing for weight, strength, and material usage.',
    whyTrend: 'Sustainable manufacturing requires more efficient parts. Generative design can create organic shapes that are impossible for humans to conceive but are lighter and stronger.',
    howConsultanciesLeverage: 'Product design firms can adopt these tools to offer superior engineering services. Management consultants can advise on the supply chain implications of using additive manufacturing for these complex parts.',
    affectedVerticals: ['v4', 'v9'],
    sourceUrl: 'https://example.com/generative-design',
    status: 'current',
    dateAdded: '2023-11-02T10:30:00Z',
    author: 'Engineering.com',
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't9',
    title: 'AI in Media Content Creation',
    justificationSummary: 'Media companies are using AI to automate video editing, scriptwriting, and even voice acting.',
    whyTrend: 'The demand for content is insatiable, but production costs are high. AI tools can democratize high-quality content creation and drastically reduce post-production times.',
    howConsultanciesLeverage: 'Media consultancies can help studios implement AI workflows. There is also a significant opportunity in rights management and IP protection consulting for AI-generated content.',
    affectedVerticals: ['v10', 'v5'],
    sourceUrl: 'https://example.com/ai-media-creation',
    status: 'current',
    dateAdded: '2023-11-05T15:45:00Z',
    author: 'Variety',
    imageUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't10',
    title: 'Government AI for Public Services',
    justificationSummary: 'Governments are deploying AI chatbots and decision support systems to improve citizen services and reduce bureaucratic backlogs.',
    whyTrend: 'Citizens expect the same level of digital service from government as they get from the private sector. AI can help understaffed agencies deliver better services more efficiently.',
    howConsultanciesLeverage: 'Public sector consultants can lead digital transformation projects. There is a massive need for "responsible AI" consulting to ensure fairness and transparency in government algorithms.',
    affectedVerticals: ['v8', 'v5', 'v1'],
    sourceUrl: 'https://example.com/government-ai',
    status: 'current',
    dateAdded: '2023-11-08T09:00:00Z',
    author: 'GovTech',
    imageUrl: 'https://images.unsplash.com/photo-1555848962-6e79363ec58f?auto=format&fit=crop&q=80&w=1000',
  },
];

