import { Trend, User, Vertical, Source } from './types';

export const VERTICALS: Vertical[] = [
  { id: 'v1', name: 'Healthcare', slug: 'healthcare', color: 'bg-emerald-500' },
  { id: 'v2', name: 'Financial Services', slug: 'financial-services', color: 'bg-blue-500' },
  { id: 'v3', name: 'Retail', slug: 'retail', color: 'bg-orange-500' },
  { id: 'v4', name: 'Manufacturing', slug: 'manufacturing', color: 'bg-slate-500' },
  { id: 'v5', name: 'Technology', slug: 'technology', color: 'bg-purple-500' },
  { id: 'v6', name: 'Legal', slug: 'legal', color: 'bg-indigo-500' },
  { id: 'v7', name: 'Education', slug: 'education', color: 'bg-yellow-500' },
  { id: 'v8', name: 'Government', slug: 'government', color: 'bg-red-500' },
  { id: 'v9', name: 'Energy', slug: 'energy', color: 'bg-green-500' },
  { id: 'v10', name: 'Media', slug: 'media', color: 'bg-pink-500' },
];

export const APPROVED_SOURCES = {
  frontierLabs: [
    'OpenAI Blog', 'Anthropic Blog', 'Google DeepMind Blog', 'Meta AI Blog', 
    'Mistral AI Blog', 'Cohere Blog', 'xAI Blog', 'Stability AI Blog'
  ],
  enterprise: [
    'McKinsey Insights', 'Boston Consulting Group (BCG) Insights', 'Bain & Company Insights', 
    'Harvard Business Review (HBR)', 'Gartner Research', 'Forrester Research', 
    'Deloitte Insights', 'PwC AI Publications'
  ],
  infrastructure: [
    'Databricks Blog', 'Snowflake Blog', 'dbt Labs Blog', 'NVIDIA AI Blog', 
    'Hugging Face Blog', 'Netflix Tech Blog', 'Uber Engineering Blog', 
    'Airbnb Engineering Blog', 'Microsoft Engineering Blog', 'AWS Machine Learning Blog', 
    'Google Cloud AI Blog'
  ],
  academic: [
    'arXiv', 'Stanford HAI Publications', 'MIT CSAIL Research Blog', 
    'Berkeley AI Research (BAIR) Blog', 'Carnegie Mellon AI Research', 
    'Allen Institute for AI (AI2) Blog'
  ],
  vc: [
    'Andreessen Horowitz (a16z) AI Blog', 'Sequoia Capital AI Publications', 
    'Greylock Partners AI Blog', 'Insight Partners AI Blog', 
    'Lightspeed Venture AI Blog', 'Accel AI Market Insights'
  ],
  news: [
    'MIT Technology Review', 'The Information', 'Financial Times', 
    'Bloomberg Technology', 'Wall Street Journal', 'TechCrunch', 'VentureBeat'
  ],
  policy: [
    'European Commission AI Act', 'White House AI Policy', 'OECD AI Policy Observatory', 
    'World Economic Forum', 'Brookings Institution', 'Center for Security and Emerging Technology (CSET)'
  ],
  analysts: [
    'Stratechery', 'The Pragmatic Engineer', 'Not Boring', 'AI Snake Oil', 
    'Import AI', 'The Sequence', 'Latent Space', 'Ben\'s Bites', 
    'Nathan Lambert\'s Interconnects', 'Ethan Mollick\'s One Useful Thing'
  ]
};

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Marcus Partner',
    email: 'marcus@consulting.com',
    role: 'user',
    avatar: 'https://i.pravatar.cc/150?u=marcus',
  },
  {
    id: 'u2',
    name: 'Sarah Strategy',
    email: 'sarah@consulting.com',
    role: 'user',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
  },
  {
    id: 'admin1',
    name: 'Admin User',
    email: 'admin@lighthouse.com',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?u=admin',
  },
];

export const MOCK_TRENDS: Trend[] = [
  {
    id: 't1',
    title: 'Generative AI in Regulatory Compliance',
    headline: 'GenAI Automating Complex Regulatory Reporting Workflows',
    trendCategory: 'Enterprise Adoption',
    justificationSummary: '• Financial institutions automating 40% of compliance checks\n• Shift from keyword matching to intent-based monitoring\n• Early adopters seeing significant operational cost reduction',
    whyTrend: 'Regulatory complexity is increasing globally while compliance budgets are shrinking. Generative AI offers a scalable solution to interpret and apply complex regulations in real-time, a capability that traditional rule-based systems lack.',
    howConsultanciesLeverage: 'Consultancies can offer "Compliance-as-a-Service" platforms powered by GenAI, or provide implementation services for custom compliance bots. There is also a significant opportunity in auditing these AI systems for hallucination risks.',
    analysisDetail: 'The convergence of LLMs with regulatory technology (RegTech) is creating a new paradigm. Unlike previous waves of automation that relied on structured data, GenAI can parse unstructured regulatory texts, policy documents, and communication logs. This allows for "intent-based" compliance monitoring rather than just keyword matching. However, the "black box" nature of these models poses a challenge, necessitating new governance frameworks that consultancies are well-positioned to design.',
    strategicImpact: '↓ Operating costs in compliance (30-40%)\n↑ Speed of regulatory response\nRisk of model hallucination requires human-in-the-loop',
    timeHorizon: 'Immediate (0–3 months)',
    confidenceScore: 9,
    confidenceReasoning: 'Validated by major bank deployments (JPMC, Citi) and patent filings',
    heatMapScores: {
      capabilityMaturity: 8,
      capitalBacking: 7,
      enterpriseAdoption: 6,
      regulatoryFriction: 9,
      competitiveIntensity: 8
    },
    marketValidation: 'Major banks deploying internal LLMs; RegTech startups raising Series B+',
    financialSignal: 'Compliance tech spend projected to grow 15% YoY; High ROI on automation',
    competitiveIntelligence: 'Big 4 firms launching proprietary AI compliance tools; Fintechs embedding AI',
    riskGovernance: 'High regulatory scrutiny; Hallucination risk in reporting; Data privacy concerns',
    trendMomentum: 'Accelerating',
    actionGuidance: 'Audit current compliance workflows for automation potential; Pilot internal LLM for policy queries',
    affectedVerticals: ['v2', 'v6', 'v8'],
    sourceUrl: 'https://www.ft.com/artificial-intelligence',
    additionalSources: [
      { id: 's1', title: 'The Future of RegTech', url: 'https://www2.deloitte.com/us/en/insights/industry/financial-services/regulatory-technology-regtech-fintech.html', publisher: 'Deloitte Insights', date: '2023-10-10' },
      { id: 's2', title: 'AI Principles', url: 'https://oecd.ai/en/ai-principles', publisher: 'OECD AI Policy Observatory', date: '2023-09-15' }
    ],
    status: 'current',
    dateAdded: '2023-10-15T10:00:00Z',
    author: 'Financial Times',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't2',
    title: 'AI-Driven Drug Discovery Acceleration',
    headline: 'AI Shortening Drug Discovery from Years to Months',
    trendCategory: 'Capability',
    justificationSummary: '• Discovery timelines compressed by 70%\n• "Inverse design" creating novel protein structures\n• Major pharma-tech partnerships validating approach',
    whyTrend: 'The traditional drug discovery process is prohibitively expensive and slow. AI models can predict molecular interactions with high accuracy, significantly narrowing the search space for potential candidates.',
    howConsultanciesLeverage: 'Strategy firms can advise pharma companies on "AI-first" R&D operating models. Tech consultancies can build the data infrastructure required to train proprietary models on internal research data.',
    analysisDetail: 'AI is moving beyond simple screening to de novo molecule generation. Generative models can design novel protein structures that have never existed in nature but bind perfectly to disease targets. This "inverse design" approach flips the traditional discovery model on its head. The challenge now shifts from discovery to validation, where AI is also being used to simulate clinical trials and predict patient responses.',
    strategicImpact: '↓ R&D costs per viable candidate\n↑ Patent portfolio value\nDifferentiation via speed to market',
    timeHorizon: 'Structural (1–3 years)',
    confidenceScore: 8,
    confidenceReasoning: 'Clinical trials underway for AI-designed drugs; Massive deal flow',
    heatMapScores: {
      capabilityMaturity: 7,
      capitalBacking: 9,
      enterpriseAdoption: 5,
      regulatoryFriction: 8,
      competitiveIntensity: 7
    },
    marketValidation: '$2B+ in pharma-AI partnerships in Q3; NVIDIA BioNeMo adoption',
    financialSignal: 'High capital efficiency in early-stage biotech; Premium valuations for AI-native platforms',
    competitiveIntelligence: 'Tech giants (NVIDIA, Google) entering bio-pharma; Traditional pharma acquiring AI startups',
    riskGovernance: 'FDA approval pathways for AI-generated drugs evolving; IP ownership clarity needed',
    trendMomentum: 'Accelerating',
    actionGuidance: 'Evaluate R&D data infrastructure; Partner with AI-native discovery platforms',
    affectedVerticals: ['v1', 'v5'],
    sourceUrl: 'https://blogs.nvidia.com/blog/category/deep-learning/',
    additionalSources: [
      { id: 's3', title: 'Generative AI in Pharma', url: 'https://www.mckinsey.com/industries/life-sciences/our-insights/generative-ai-in-the-pharmaceutical-industry-moving-from-hype-to-reality', publisher: 'McKinsey Insights', date: '2023-10-05' },
      { id: 's4', title: 'AlphaFold Latest', url: 'https://deepmind.google/discover/blog/alphafold-3-predicts-the-structure-and-interactions-of-all-lifes-molecules/', publisher: 'Google DeepMind Blog', date: '2023-09-20' }
    ],
    status: 'current',
    dateAdded: '2023-10-18T14:30:00Z',
    author: 'NVIDIA AI Blog',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't3',
    title: 'Hyper-Personalization in Retail at Scale',
    headline: 'Generative AI Enabling 1:1 Retail Personalization',
    trendCategory: 'Enterprise Adoption',
    justificationSummary: '• Real-time content generation for individual shoppers\n• Shift from predictive to generative personalization\n• Conversion rate uplift of 15-20% in pilots',
    whyTrend: 'Consumers increasingly expect personalized experiences. GenAI allows retailers to generate unique product descriptions, images, and marketing copy for every user on the fly, increasing conversion rates.',
    howConsultanciesLeverage: 'Marketing consultancies can help brands design "segment-of-one" customer journeys. Implementation partners are needed to integrate GenAI tools with existing e-commerce platforms and CDPs.',
    analysisDetail: 'The shift is from "predictive" personalization (guessing what you might like) to "generative" personalization (creating what you want). This involves real-time rendering of products in contexts relevant to the user (e.g., showing a tent in a forest for a hiker vs. a backyard for a family). This level of personalization requires a robust data foundation and low-latency inference infrastructure.',
    strategicImpact: '↑ Customer Lifetime Value (CLV)\n↑ Marketing ROI\nDifferentiation via unique customer experience',
    timeHorizon: 'Emerging (3–12 months)',
    confidenceScore: 7,
    confidenceReasoning: 'Early pilots successful; Infrastructure costs still high',
    heatMapScores: {
      capabilityMaturity: 6,
      capitalBacking: 8,
      enterpriseAdoption: 7,
      regulatoryFriction: 5,
      competitiveIntensity: 9
    },
    marketValidation: 'Major e-commerce platforms integrating GenAI; Ad-tech pivot to generative',
    financialSignal: 'Marketing spend shifting to AI tools; CAC reduction focus',
    competitiveIntelligence: 'Amazon/Shopify embedding AI features; Startups disrupting agency model',
    riskGovernance: 'Brand safety risks in auto-generation; Consumer privacy backlash',
    trendMomentum: 'Accelerating',
    actionGuidance: 'Pilot generative product imagery; Audit customer data platform (CDP) readiness',
    affectedVerticals: ['v3', 'v10'],
    sourceUrl: 'https://www.bcg.com/capabilities/artificial-intelligence/insights',
    additionalSources: [
      { id: 's5', title: 'Personalization at Scale', url: 'https://hbr.org/2023/05/how-generative-ai-will-change-sales', publisher: 'Harvard Business Review', date: '2023-10-12' }
    ],
    status: 'current',
    dateAdded: '2023-10-20T09:15:00Z',
    author: 'BCG Insights',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't4',
    title: 'Autonomous Supply Chain Agents',
    headline: 'Autonomous Agents Negotiating Logistics Without Humans',
    trendCategory: 'Infrastructure',
    justificationSummary: '• Agents executing trades and re-routing autonomously\n• Self-healing supply networks emerging\n• 24/7 optimization for cost and carbon',
    whyTrend: 'Supply chain disruptions are becoming the norm. Autonomous agents provide the speed and responsiveness needed to adapt to shocks in real-time, which human teams cannot match.',
    howConsultanciesLeverage: 'Operations consultants can redesign supply chain processes to accommodate autonomous decision-making. Change management is critical here as human roles shift from execution to oversight.',
    analysisDetail: 'Unlike traditional optimization software that suggests actions, autonomous agents execute them. They can negotiate spot rates with carriers, trigger re-orders based on predictive demand, and dynamically adjust production schedules. The key innovation is the ability of these agents to communicate with each other across organizational boundaries, creating a self-healing supply network.',
    strategicImpact: '↓ Logistics costs (10-15%)\n↑ Resilience to shocks\nRisk of algorithmic collusion/error',
    timeHorizon: 'Emerging (3–12 months)',
    confidenceScore: 6,
    confidenceReasoning: 'Technology viable but enterprise trust/adoption lagging',
    heatMapScores: {
      capabilityMaturity: 5,
      capitalBacking: 6,
      enterpriseAdoption: 3,
      regulatoryFriction: 4,
      competitiveIntensity: 5
    },
    marketValidation: 'Logistics giants piloting agentic frameworks; Microsoft/SAP integration',
    financialSignal: 'Supply chain software spend increasing; Focus on working capital optimization',
    competitiveIntelligence: 'Digital-native logistics firms gaining share; Legacy ERPs adding agent layers',
    riskGovernance: 'Liability for agent decisions; Multi-agent coordination failure risks',
    trendMomentum: 'Early Signal',
    actionGuidance: 'Identify low-risk autonomous workflows; Pilot agent-based procurement',
    affectedVerticals: ['v4', 'v3', 'v9'],
    sourceUrl: 'https://www.gartner.com/en/supply-chain/insights',
    additionalSources: [
      { id: 's6', title: 'Supply Chain Optimization', url: 'https://devblogs.microsoft.com/engineering/', publisher: 'Microsoft Engineering Blog', date: '2023-10-25' }
    ],
    status: 'current',
    dateAdded: '2023-10-22T11:45:00Z',
    author: 'Gartner Research',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't5',
    title: 'AI in Predictive Maintenance for Energy Grids',
    headline: 'AI Predicting Grid Failures Weeks in Advance',
    trendCategory: 'Infrastructure',
    justificationSummary: '• Predictive accuracy preventing major outages\n• Managing renewable energy load variability\n• Shift from reactive to predictive maintenance',
    whyTrend: 'Aging infrastructure and the integration of renewable energy sources are stressing power grids. AI provides the predictive capabilities needed to maintain reliability in a complex, decentralized grid.',
    howConsultanciesLeverage: 'Engineering consultancies can implement IoT sensor networks and AI analytics platforms. Strategy firms can advise on the business case for grid modernization investments.',
    analysisDetail: 'The grid is becoming a bi-directional network with the addition of solar panels and EVs. Traditional grid management software struggles with this complexity. AI models trained on historical weather data, load patterns, and sensor readings can predict transformer failures weeks in advance, allowing for planned maintenance instead of emergency repairs.',
    strategicImpact: '↓ Maintenance CapEx/OpEx\n↑ Grid reliability metrics\nRegulatory compliance improvement',
    timeHorizon: 'Structural (1–3 years)',
    confidenceScore: 9,
    confidenceReasoning: 'Mandated by grid modernization policies; Proven ROI',
    heatMapScores: {
      capabilityMaturity: 9,
      capitalBacking: 8,
      enterpriseAdoption: 8,
      regulatoryFriction: 6,
      competitiveIntensity: 6
    },
    marketValidation: 'Utilities globally deploying AI at scale; Gov funding support',
    financialSignal: 'Infrastructure investment supercycle; High cost of failure driving spend',
    competitiveIntelligence: 'Siemens/GE/Schneider doubling down on AI grid tech; Clean-tech startups',
    riskGovernance: 'Cybersecurity of AI-controlled grid assets; Model bias in load shedding',
    trendMomentum: 'Mainstream Adoption',
    actionGuidance: 'Invest in sensor data quality; Partner with grid-edge AI vendors',
    affectedVerticals: ['v9', 'v8'],
    sourceUrl: 'https://aws.amazon.com/blogs/machine-learning/',
    additionalSources: [
      { id: 's7', title: 'Grid Modernization', url: 'https://cloud.google.com/blog/products/ai-machine-learning', publisher: 'Google Cloud AI Blog', date: '2023-10-28' }
    ],
    status: 'current',
    dateAdded: '2023-10-25T16:20:00Z',
    author: 'AWS Machine Learning Blog',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't6',
    title: 'Legal Tech: Automated Contract Review',
    headline: 'AI Commoditizing Routine Legal Contract Review',
    trendCategory: 'Enterprise Adoption',
    justificationSummary: '• Contract review time reduced by 80%\n• Semantic understanding vs keyword search\n• Shift to high-value advisory work',
    whyTrend: 'Legal review is a major bottleneck in business transactions. AI can handle routine contract review faster and more consistently than junior lawyers, freeing them for higher-value work.',
    howConsultanciesLeverage: 'Legal tech consultancies can help firms select and train AI models on their specific contract templates. There is also a market for "legal operations" consulting to optimize workflows around these new tools.',
    analysisDetail: 'AI is not just searching for keywords; it is understanding the semantic meaning of clauses. It can identify "poison pill" clauses, compare terms against a company\'s playbook, and suggest redlines. This reduces the cost of due diligence in M&A and accelerates sales cycles by speeding up contract negotiations.',
    strategicImpact: '↓ Legal spend (external & internal)\n↑ Deal velocity\nRisk of over-reliance on automated review',
    timeHorizon: 'Immediate (0–3 months)',
    confidenceScore: 9,
    confidenceReasoning: 'Widespread adoption in Big Law and corporate legal',
    heatMapScores: {
      capabilityMaturity: 9,
      capitalBacking: 8,
      enterpriseAdoption: 9,
      regulatoryFriction: 7,
      competitiveIntensity: 9
    },
    marketValidation: 'Harvey AI, Ironclad, etc. seeing massive growth; Law firms licensing tools',
    financialSignal: 'Legal tech investment holding steady; Billable hour model disruption',
    competitiveIntelligence: 'Legal-specific LLMs vs General LLMs; Incumbents acquiring startups',
    riskGovernance: 'Client confidentiality; "Practice of law" regulatory questions',
    trendMomentum: 'Mainstream Adoption',
    actionGuidance: 'Implement AI contract review for NDAs/MSAs immediately; Train legal ops',
    affectedVerticals: ['v6', 'v2', 'v5'],
    sourceUrl: 'https://hbr.org/topic/law-and-legal-issues',
    additionalSources: [
      { id: 's8', title: 'Legal AI Trends', url: 'https://www.theinformation.com/topics/artificial-intelligence', publisher: 'The Information', date: '2023-11-01' }
    ],
    status: 'current',
    dateAdded: '2023-10-28T08:00:00Z',
    author: 'Harvard Business Review',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't7',
    title: 'AI-Powered Personalized Learning',
    headline: 'Adaptive AI Tutors Closing Education Gaps',
    trendCategory: 'Capability',
    justificationSummary: '• 1:1 tutoring at mass scale\n• Real-time curriculum adaptation\n• Closing achievement gaps via personalization',
    whyTrend: 'The "one-size-fits-all" model of education is failing many students. AI enables mass personalization, potentially closing achievement gaps and improving learning outcomes.',
    howConsultanciesLeverage: 'Education consultants can help institutions integrate AI tools into their curriculum. There is also a need for policy consulting to address data privacy and ethical concerns in student data.',
    analysisDetail: 'Adaptive learning systems use knowledge graphs to map a student\'s understanding. If a student struggles with a concept, the AI doesn\'t just repeat the lesson; it offers a different explanation, a prerequisite concept, or a practice problem. This continuous feedback loop keeps students in the "zone of proximal development" for optimal learning.',
    strategicImpact: '↑ Student outcomes/retention\n↓ Cost of remedial education\nDifferentiation for EdTech platforms',
    timeHorizon: 'Emerging (3–12 months)',
    confidenceScore: 8,
    confidenceReasoning: 'Khan Academy/Duolingo success cases; Strong VC backing',
    heatMapScores: {
      capabilityMaturity: 7,
      capitalBacking: 8,
      enterpriseAdoption: 6,
      regulatoryFriction: 8,
      competitiveIntensity: 7
    },
    marketValidation: 'EdTech unicorns integrating AI tutors; Schools piloting adaptive platforms',
    financialSignal: 'EdTech funding rebounding for AI-focused startups',
    competitiveIntelligence: 'OpenAI partnering with education non-profits; Big Tech entering LMS market',
    riskGovernance: 'Student data privacy (COPPA); Algorithmic bias in grading/tracking',
    trendMomentum: 'Accelerating',
    actionGuidance: 'Pilot AI tutors for remedial support; Update data privacy policies',
    affectedVerticals: ['v7', 'v5'],
    sourceUrl: 'https://hai.stanford.edu/news',
    additionalSources: [
      { id: 's9', title: 'AI in Education', url: 'https://www.csail.mit.edu/news', publisher: 'MIT CSAIL Research Blog', date: '2023-11-03' }
    ],
    status: 'current',
    dateAdded: '2023-10-30T13:10:00Z',
    author: 'Stanford HAI',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't8',
    title: 'Generative Design in Manufacturing',
    headline: 'AI Designing Lighter, Stronger Parts Autonomously',
    trendCategory: 'Capability',
    justificationSummary: '• Weight reduction of 20-40%\n• Impossible geometries now manufacturable\n• Sustainability via material efficiency',
    whyTrend: 'Sustainable manufacturing requires more efficient parts. Generative design can create organic shapes that are impossible for humans to conceive but are lighter and stronger.',
    howConsultanciesLeverage: 'Product design firms can adopt these tools to offer superior engineering services. Management consultants can advise on the supply chain implications of using additive manufacturing for these complex parts.',
    analysisDetail: 'Generative design software takes constraints (loads, materials, manufacturing methods) as input and "evolves" a design solution. This often results in alien-looking, organic structures that minimize material usage while maximizing structural integrity. This is particularly valuable in aerospace and automotive industries where weight reduction directly translates to fuel efficiency.',
    strategicImpact: '↓ Material costs\n↑ Product performance/efficiency\nDifferentiation via novel design',
    timeHorizon: 'Structural (1–3 years)',
    confidenceScore: 8,
    confidenceReasoning: 'Standard in aerospace/auto R&D; Software maturity high',
    heatMapScores: {
      capabilityMaturity: 8,
      capitalBacking: 6,
      enterpriseAdoption: 7,
      regulatoryFriction: 3,
      competitiveIntensity: 5
    },
    marketValidation: 'Autodesk/PTC/Siemens integrating generative features; Airbus/GM adoption',
    financialSignal: 'High value-add in discrete manufacturing; Premium pricing for lightweight parts',
    competitiveIntelligence: 'CAD vendors racing to add AI; Startups focusing on specific verticals',
    riskGovernance: 'Manufacturability validation; IP of AI-generated designs',
    trendMomentum: 'Accelerating',
    actionGuidance: 'Train engineering teams on generative tools; Evaluate additive mfg capacity',
    affectedVerticals: ['v4', 'v9'],
    sourceUrl: 'https://www.technologyreview.com/topic/artificial-intelligence/',
    additionalSources: [
      { id: 's10', title: 'Generative Design', url: 'https://blogs.nvidia.com/', publisher: 'NVIDIA AI Blog', date: '2023-11-04' }
    ],
    status: 'current',
    dateAdded: '2023-11-02T10:30:00Z',
    author: 'MIT Technology Review',
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't9',
    title: 'AI in Media Content Creation',
    headline: 'AI Democratizing High-Fidelity Media Production',
    trendCategory: 'Capability',
    justificationSummary: '• Post-production costs slashed\n• Content atomization at scale\n• IP rights landscape shifting',
    whyTrend: 'The demand for content is insatiable, but production costs are high. AI tools can democratize high-quality content creation and drastically reduce post-production times.',
    howConsultanciesLeverage: 'Media consultancies can help studios implement AI workflows. There is also a significant opportunity in rights management and IP protection consulting for AI-generated content.',
    analysisDetail: 'AI tools can now generate B-roll footage, dub content into multiple languages with the original actor\'s voice, and even de-age actors. This allows for "content atomization," where a single piece of content is automatically repurposed for different platforms and audiences. However, the legal landscape regarding the copyright of AI-generated works remains unsettled.',
    strategicImpact: '↓ Production costs (50%+)\n↑ Content volume/velocity\nRisk of IP infringement lawsuits',
    timeHorizon: 'Immediate (0–3 months)',
    confidenceScore: 9,
    confidenceReasoning: 'Explosion of tools (Runway, Pika, Sora); Hollywood adoption',
    heatMapScores: {
      capabilityMaturity: 8,
      capitalBacking: 10,
      enterpriseAdoption: 7,
      regulatoryFriction: 9,
      competitiveIntensity: 10
    },
    marketValidation: 'Studios using AI for VFX/dubbing; Marketing agencies adopting en masse',
    financialSignal: 'Media tech valuation reset; Shift from labor to compute spend',
    competitiveIntelligence: 'Adobe vs Startups; Social platforms integrating creation tools',
    riskGovernance: 'Deepfake risks; Copyright/IP litigation; Talent displacement',
    trendMomentum: 'Mainstream Adoption',
    actionGuidance: 'Establish AI content guidelines; Pilot AI for localization/versioning',
    affectedVerticals: ['v10', 'v5'],
    sourceUrl: 'https://a16z.com/category/ai/',
    additionalSources: [
      { id: 's11', title: 'AI in Film', url: 'https://netflixtechblog.com/', publisher: 'Netflix Tech Blog', date: '2023-11-06' }
    ],
    status: 'current',
    dateAdded: '2023-11-05T15:45:00Z',
    author: 'a16z AI Blog',
    imageUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=1000',
  },
  {
    id: 't10',
    title: 'Government AI for Public Services',
    headline: 'GovTech AI Improving Citizen Service Delivery',
    trendCategory: 'Enterprise Adoption',
    justificationSummary: '• Bureaucratic backlogs reduced\n• 24/7 citizen support via AI\n• Focus on "Responsible AI" frameworks',
    whyTrend: 'Citizens expect the same level of digital service from government as they get from the private sector. AI can help understaffed agencies deliver better services more efficiently.',
    howConsultanciesLeverage: 'Public sector consultants can lead digital transformation projects. There is a massive need for "responsible AI" consulting to ensure fairness and transparency in government algorithms.',
    analysisDetail: 'AI is being used to triage 311 calls, process tax returns, and even assist judges in sentencing (though this is controversial). The key challenge is ensuring that these systems do not perpetuate historical biases found in training data. "Explainable AI" is a critical requirement for public sector deployments to maintain public trust.',
    strategicImpact: '↓ Administrative burden\n↑ Citizen satisfaction/trust\nRisk of bias/discrimination lawsuits',
    timeHorizon: 'Emerging (3–12 months)',
    confidenceScore: 7,
    confidenceReasoning: 'Global initiatives (Singapore, UK, EU); Procurement cycles slow',
    heatMapScores: {
      capabilityMaturity: 6,
      capitalBacking: 5,
      enterpriseAdoption: 4,
      regulatoryFriction: 10,
      competitiveIntensity: 4
    },
    marketValidation: 'Gov-specific cloud zones adding AI; Public sector pilots increasing',
    financialSignal: 'GovTech spending resilient to recession; Large contract values',
    competitiveIntelligence: 'System integrators building AI practices; Sovereign AI clouds emerging',
    riskGovernance: 'Algorithmic bias; Data sovereignty; Public accountability',
    trendMomentum: 'Accelerating',
    actionGuidance: 'Align with NIST/EU AI Act frameworks; Focus on low-risk use cases first',
    affectedVerticals: ['v8', 'v5', 'v1'],
    sourceUrl: 'https://www.brookings.edu/topic/artificial-intelligence/',
    additionalSources: [
      { id: 's12', title: 'AI Governance', url: 'https://oecd.ai/en/ai-principles', publisher: 'OECD AI Policy Observatory', date: '2023-11-09' }
    ],
    status: 'current',
    dateAdded: '2023-11-08T09:00:00Z',
    author: 'Brookings Institution',
    imageUrl: 'https://images.unsplash.com/photo-1555848962-6e79363ec58f?auto=format&fit=crop&q=80&w=1000',
  },
];

